project:
  type: website
  output-dir: docs
  resources:
    - "files/*"

website:
  title: "Rebekah Jones"
  site-url: "index.qmd"
  favicon: assets/favicon.png
  search: false
  google-analytics: "G-SWWDQ72BXF"
  navbar:
    right:
      - href: research/
        text: Research
      - href: cv/
        text: C.V.

  page-footer:
    background: light # or `dark`
    left: Copyright 2025, . <br> Built adopting code in part from [Zachary Lorico Hertz](https://zacharylhertz.github.io/).

format:
  html:
    theme:
      - cosmo
      - brand
    css: assets/global_styles.css
    toc: true
    page-layout: full

editor: visual

